// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCz9r84HLS1GZ4QelTxrZUR533Szczur_o",
      authDomain: "test1fcm-d0e1a.firebaseapp.com",
      projectId: "test1fcm-d0e1a",
      storageBucket: "test1fcm-d0e1a.appspot.com",
      messagingSenderId: "182921035370",
      appId: "1:182921035370:web:82c2b1075ffe14992ad413",
      measurementId: "G-C54LRT9LGJ");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbM32pJy0J8bQAHHXfZ3sPVXGKdC8aZAU',
    appId: "1:182921035370:android:da895d38f0e8a34d2ad413",
    messagingSenderId: "182921035370",
    projectId: "test1fcm-d0e1a",
    storageBucket: "test1fcm-d0e1a.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7K1OEFXoMoFlkxKndjqv1L3N9Jswooug',
    appId: '1:1071852886258:ios:0759d2d6b0411f38f6d86b',
    messagingSenderId: "182921035370",
    projectId: "test1fcm-d0e1a",
    storageBucket: "test1fcm-d0e1a.appspot.com",
    iosBundleId: 'com.kaizen.erecrutement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7K1OEFXoMoFlkxKndjqv1L3N9Jswooug',
    appId: '1:1071852886258:ios:a65b1073d7814795f6d86b',
    messagingSenderId: '182921035370',
    projectId: "test1fcm-d0e1a",
    storageBucket: "test1fcm-d0e1a.appspot.com",
    iosBundleId: 'com.kaizen.erecrutement.RunnerTests',
  );
}
